name: Publish Docker image

on:
  push:
    branches:
      - 'v*.*.*'

jobs:
  publish:
    name: Push Docker image to Docker Hub
    runs-on:
      - X64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        shell: bash
        env:
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        run: |
          docker build . -t aldmbmtl/cluster-builder:$SOURCE_BRANCH
          docker push aldmbmtl/cluster-builder:$SOURCE_BRANCH